name: Build/Test

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      part:
        required: false
        default: ''

jobs:
  build:
    name: Build the library and run tests
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04, ubuntu-22.04, ubuntu-24.04-arm]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-filelock python3-pytest

      - name: Build and install library
        run: |
          sudo python3 setup.py install

      - name: Run unit tests
        run: |
          pytest-3 .

      - name: Run functional tests (file backend)
        run: |
          python3 scripts/func_test.py file /dev/shm/tosc_data
